#! /usr/bin/env syno-shell
#! syno-shell -i bash -p bash gh

set -euo pipefail

if [ $# -eq 0 ]; then
    echo "Usage: query-prs.sh <from YYYY-MM-DD> <to YYYY-MM-DD>"
    exit 1
fi

from_date="$1"
to_date="$2"
pr_fields="number,title,author,url"
pr_template="{{range .}}- [#{{.number}}]({{.url}}) {{.title}} ([@{{.author.login}}](https://github.com/{{.author.login}})){{printf \"\n\"}}{{end}}"
tracking_issue_template="{{range .}}- [#{{.number}}]({{.url}}) {{.title}}{{printf \"\n\"}}{{end}}"

# Lists the PRs merged from a repository between certain dates, optionally filtered by labels
list_merged_prs() {
    if [ $# -gt 1 ]; then
        repo="$1"
        labels="$2"
        gh pr list -R "$repo" --search "is:merged merged:$from_date..$to_date label:\"$labels\"" --json "$pr_fields" --template "$pr_template"
    else
        repo="$1"
        gh pr list -R "$repo" --search "is:merged merged:$from_date..$to_date" --json "$pr_fields" --template "$pr_template"
    fi
}

# Lists the PRs opened on a repository
list_opened_prs() {
    if [ $# -gt 1 ]; then
        repo="$1"
        labels="$2"
        gh pr list -R "$repo" --search "is:unmerged created:$from_date..$to_date label:\"$labels\"" --json "$pr_fields" --template "$pr_template"
    else
        repo="$1"
        gh pr list -R "$repo" --search "is:unmerged created:$from_date..$to_date" --json "$pr_fields" --template "$pr_template"
    fi
}

# Lists all of the tracking issues opened on syno.dev within the specified dates
list_new_tracking_issues() {
    gh issue list -R "synopkg/syno.dev" --search "created:$from_date..$to_date label:tracking" --json "$pr_fields" --template "$tracking_issue_template"
}

cat << EOF
# This Month in Syno Docs - #NUMBER - MONTH YEAR

## Community
The Documentation Team can be found in a number of places. Check the [Documentation Team page](https://synopkg.github.io/community/teams/documentation.html) and drop in if you'd like to contribute!

## Projects

## How You Can Help
If you like what we're doing, consider [joining the documentation team](https://synopkg.github.io/community/teams/documentation) or [donating to the SynoPKG Foundation's documentation project on Open Collective](https://opencollective.com/synopkg/projects/documentation-project) to fund ongoing maintenance and development of learning materials and other documentation.

## RFCs

## Documentation PRs Merged

# AUTOGENERATED

EOF

echo "## PRs"
echo

echo "### SynoPKG/syno"
list_merged_prs "synopkg/syno" "documentation"
echo

echo "### SynoPKG/synopkgs"
list_merged_prs "synopkg/synopkgs" "6.topic: documentation"
list_merged_prs "synopkg/synopkgs" "8.has: documentation"
echo

echo "### SynoPKG/syno-pills"
list_merged_prs "synopkg/syno-pills"
echo

echo "### SynoPKG/syno.dev"
list_merged_prs "synopkg/syno.dev"
echo

echo "## RFCs"
echo

echo "### Opened (manually check for relevance)"
list_opened_prs "synopkg/rfcs"
echo

echo "### Accepted (manually check for relevance)"
list_merged_prs "synopkg/rfcs"
echo

echo "## New Tracking Issues"
list_new_tracking_issues
echo
