name: "Test"

on:
  push: {}
  pull_request: {}

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: cachix/install-syno-action@v23
      with:
        syno_path: synopkgs=channel:synopkg-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: syno.dev
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run linkcheck
      run: syno-shell --run "make linkcheck"
  codeblock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       fetch-depth: 0
    - uses: cachix/install-syno-action@v23
      with:
        syno_path: synopkgs=channel:synopkg-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: syno.dev
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run builder
      run: syno-shell --run "make dummy"
    - name: Test code blocks
      run: syno-shell --run "./run_code_block_tests.sh"
